# Generated by Django 2.2.10 on 2020-05-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10000)),
                ('timeStamp', models.DateTimeField()),
                ('active_Solvers', models.IntegerField()),
                ('Tags', models.CharField(max_length=10000)),
                ('price', models.CharField(max_length=15)),
                ('contents', models.TextField()),
                ('slug', models.CharField(max_length=130)),
            ],
        ),
    ]
