# Generated by Django 2.2.10 on 2020-05-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='pic',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
